### PR TITLE
Feature/libcir 90

### PR DESCRIPTION
**Pull request by phammer-umd**

### CODE REVIEW

**Comment by mohideen** [comment]
This PR includes changes to dspace/config/crosswalks/DIM2DataCite.xsl. This crosswalk is not being used in mdsoar. We use EZID as our Datacite provider and our dspace.cfg is configured to use dspace/config/crosswalks/DIM2EZID.xsl.
https://github.com/umd-lib/mdsoar/blob/mdsoar-develop/dspace/config/dspace.cfg#L551

I would suggest the changes to this file be reverted to avoid any confusion in the future as to which crosswalks are used by mdsoar.

**Comment by phammer-umd** [comment]
DIM2DataCite already had all but 3 of the 11 data type conversions and reverting them would only require us to identify and post those 3 changes again.  My recommendation would be to leave it and possibly include a comment in both xsl files as to the name of the cfg file to consult to identify which crosswalk file is in use by dspace.

**Comment by mohideen** [comment]
Adding the comment would definitely be helpful, but I would still suggest reverting the actual changes for two reasons:
1. That would mean one additional merge conflict to handle during dspace upgrades.
2. All the previous mdsoar crosswalk customizations has been going only to the DIM2EZID,
https://github.com/phammer-umd/mdsoar/commits/feature/LIBCIR-90/dspace/config/crosswalks/DIM2EZID.xsl, so we would have port all of them, if we switch to Datacite.

**Comment by phammer-umd** [comment]
Done

**Pull request merged**
